#ifndef ALL_METHOD_H
#define ALL_METHOD_H

#include "absmethod.h"
#include "dedup.h"
#include "finesse.h"
#include "odess.h"
#include "palantir.h"
#include "bisearch.h"
#include "ntransform.h"

#include "odess_mi_baseline.h"
#include "odess_mi_baseline2.h"
#include "odess_mi_df.h"
#include "odess_mi_baseline3.h"
#include "odessMLLog2.h"
#include "odessMLLess4.h"
#include "Tree/TreeCut.h"
#include "Tree/TreeGreedy.h"
#include "Tree/TreeCutLayer.h"
#include "AllGreedy.h"
#include "Tree/TreeCache.h"
#include "Tree/TreeCache2.h"
#include "Tree/SubTreeReduction.h"
#include "AllGreedyLRU.h"
#include "AllGreedyLFU.h"

#include "Offline/offline_greedy.h"
#include "Offline/offline_treecut.h"
#include "Offline/offline_treecutlayer.h"
#include "Offline/offline_tree_Feature.h"
#include "Offline/offline_treecache.h"
#include "Offline/offline_treecutlayerIgnore.h"
#include "Offline/offline_tree_Feature_lru.h"

#include "Thread/design1.h"
#include "Thread/design3_R.h"
#include "Thread/design3.h"
#include "Thread/design3_G.h"
#include "Thread/design3_S.h"
#include "Thread/greedy.h"
#endif
